# name: GitHub Actions Demo
# run-name: ${{ github.actor }} is testing out GitHub Actions ðŸš€
# on: [push]
# jobs:
#   Explore-GitHub-Actions:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Use secret
#         run: |
#           echo "${{ secrets.API_UPDATE_SECRET }}" > .env
#           cat .env
#           echo "ðŸ This job's status is ${{ job.status }}."

name: PR Comment via dispatch

on:
  workflow_dispatch:
    inputs:
      myInput:
        description: 'Example input'
        required: true
        default: 10

jobs:
  pr-trigger:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}  # or use a PAT if needed
    steps:
      # - name: Print success by calling action
      #   uses: gkgth/helm-test-apps/.github/actions/trigger-pr-checker@main
      #   id: trigger_pr_action
      #   run: echo "âœ… Keyword /run-tests matched! Running job..."

      - name: Print commenter
        run: echo "Comment made by - $GITHUB_ACTOR"

      - name: Print repo
        run: echo "Repo - $GITHUB_REPOSITORY"

      - name: Get PR branch name
        id: get_branch
        run: |
          echo "Received PR: ${{ github.event.inputs.myInput }}"
          PR_NUMBER=${{ github.event.inputs.myInput }}
          echo "${PR_NUMBER}"
          BRANCH=$(curl -s -H "Authorization: token ${GH_TOKEN}" \
            https://api.github.com/repos/${{ github.repository }}/pulls/${PR_NUMBER} \
            | jq -r .head.ref)
          echo "branch_name=$BRANCH" >> $GITHUB_OUTPUT
          echo "variable from root job $gk_newvar"
          echo "variable from root job ${{ steps.parentjobid.outputs.gk_newvar }}"

      - name: Use branch name
        run: echo "Source branch is ${{ steps.get_branch.outputs.branch_name }}"
